# USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/energy/phone_pro_qi/BoardConfigVendor.mk

# Device configuration
TARGET_BOARD_PLATFORM := mt6592
TARGET_NO_BOOTLOADER := true
DEVICE_RESOLUTION := 1080x1920
TARGET_BOOTLOADER_BOARD_NAME := energy_phone_pro_qi
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := cortex-a7

# TWRP configuration
BOARD_HAS_LARGE_FILESYSTEM := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_BRIGHTNESS_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/sdcard1"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard1"

TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/virtual/android_usb/android0/f_mass_storage/lun%d/file"
TW_USE_LEGACY_BATTERY_SERVICES := true
TW_NO_USB_STORAGE := false
BOARD_HAS_NO_REAL_SDCARD := true


TARGET_USERIMAGES_USE_EXT4 := true
# TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false


# Sizes and offsets
# make_ext4fs requires numbers in dec format
BOARD_BOOTIMAGE_PARTITION_SIZE := 10485760
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 947912704
BOARD_USERDATAIMAGE_PARTITION_SIZE := 30080499712
BOARD_FLASH_BLOCK_SIZE := 131072

# mkbootimg parameters
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_SECOND_OFFSET := 0x00f00000
BOARD_TAGS_OFFSET := 0x00000100

BOARD_SEPOLICY_DIRS := \
       device/energy/phone_pro_qi/sepolicy

BOARD_SEPOLICY_UNION := \
       device.te \
       app.te \
       system.te \
       file_contexts

TARGET_PREBUILT_KERNEL := device/energy/phone_pro_qi/kernel
TARGET_RECOVERY_FSTAB := device/energy/phone_pro_qi/rootdir/recovery.fstab

BOARD_HAS_NO_SELECT_BUTTON := true

BOARD_CUSTOM_BOOTIMG_MK := device/energy/phone_pro_qi/bootimg.mk
BOARD_MKBOOTIMG_ARGS := --board 2ee33ae

TARGET_KMODULES := true

BOARD_EGL_CFG := device/energy/phone_pro_qi/egl.cfg
USE_OPENGL_RENDERER := true
BOARD_EGL_WORKAROUND_BUG_10194508 := true
TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true

# MTK Hardware
# BOARD_HAS_MTK_HARDWARE := true
# MTK_HARDWARE := true
# COMMON_GLOBAL_CFLAGS += -DMTK_AUDIO -DMTK_AUDIO_ADPCM_SUPPORT -DHAVE_AEE_FEATURE -DMTK_VIDEO_HEVC_SUPPORT
# COMMON_GLOBAL_CPPFLAGS += -DMTK_AUDIO -DMTK_AUDIO_ADPCM_SUPPORT -DHAVE_AEE_FEATURE -DMTK_VIDEO_HEVC_SUPPORT


# Offline charging
BOARD_CHARGING_MODE_BOOTING_LPM := /sys/class/BOOT/BOOT/boot/boot_mode

# BOARD_RIL_CLASS := ../../../device/energy/phone_pro_qi/ril/

# BOARD_CONNECTIVITY_VENDOR := MediaTek
# BOARD_CONNECTIVITY_MODULE := conn_soc

TARGET_CPU_MEMCPY_OPT_DISABLE := true

# WiFi config
# WPA_SUPPLICANT_VERSION := VER_0_8_X
# BOARD_HOSTAPD_DRIVER := NL80211
# BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_mt66xx
# BOARD_WPA_SUPPLICANT_DRIVER := NL80211
# BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_mt66xx
# WIFI_DRIVER_FW_PATH_PARAM:="/dev/wmtWifi"
# WIFI_DRIVER_FW_PATH_STA:=STA
# WIFI_DRIVER_FW_PATH_AP:=AP
# WIFI_DRIVER_FW_PATH_P2P:=P2P

# Bluetooth
# BOARD_HAVE_BLUETOOTH := true
# BOARD_HAVE_BLUETOOTH_MTK := true
# BOARD_BLUETOOTH_DOES_NOT_USE_RFKILL := true
# BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/energy/phone_pro_qi/bluetooth
